### ISSUE TITLE
Evaluation problem

### ISSUE THREAD

**Issue by Chantec** [rhtm02/PU-Transformer#5]
Hello,i am sorry to trouble you again.The evaluation indicators I got were very big.
The cd (1e-3) 2.58328833, hd 39.47240673, p2f std  64.02663141.
It's very different from your indicators.
When i trained the model i used PU1K dataset,and when i evaluation i use PUGAN dataset,Do you know what the reason is?

**Comment by Chantec** [comment]
And when i trained , the cd loss is also big ,about 1.1(1e-3)

When i evaluate, i used code that
`   data=load_xyz_file(os.path.join(input_dir, file))`
`    out=model(data)`
`    save_xyz_file(out[0],f'./result/{file}.xyz')`
Am I wrong here?I see the paper first step that cut the input point cloud into multiple seed patches,but i did not find those code yet,so i did not use it.

**Comment by Chantec** [comment]
And i had changed your code in utils.py
from
`from pointnet_utils import pointnet2_utils`
to
`from pointnet2_ops  import pointnet2_utils`
because i can not find the module pointnet_utils in Pointnet2_PyTorch, am i wrong here?

**Comment by rhtm02** [comment]
First of all, I'm really sorry that it's an issue caused by my code not being a complete version. Of course, the resulting code exists, but the code has not been updated in the current repository. 
Due to personal reasons, I think it will take some time to release the complete version of the updated code.

The upsampling process is as follows:
1. Create patches through KNN based on random seeds (256 points)
2. Upsampling patches created (256 -> 1024)
3. Merge upsampled points (1024 * patch_num)
4. Create 4096 points through fps (1024 * patch_num -> 4096)

Perhaps fps-related or knn-related functions exist in the corresponding repo. [link](https://github.com/rhtm02/PU-Transformer/blob/main/pointops/functions.py)

What you need to consider when you merge is that when you divide it into patches and make it into inputs, you need to store the distance traveled in parallel, divided for normalize. This is because these two values are used to restore them to their original state later.

**Comment by rhtm02** [comment]
No pointnet-related repositories were used. So it doesn't matter if you remove the import part.

**Comment by Chantec** [comment]
Thanks for your reply,I'll try later using the steps you said.
And I wonder if the train.py is the final code?

**Comment by rhtm02** [comment]
Yes train.py is final code

**Comment by Chantec** [comment]
Ok,Thank you very much!
